spring.application.name=application

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.id.optimizer.pooled.prefer_lo=true

api.security.token.secret=${api.security.token.secret}
logging.level.org.springframework.security=TRACE

server.port=8080

webpush.vapid.public.key=${VAPID_PUBLIC_KEY}
webpush.vapid.private.key=${VAPID_PRIVATE_KEY}
webpush.vapid.subject=${VAPID_SUBJECT}

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.metrics.tags.environment=development
