-- ============================================================
-- LunaLink - Init Script (PostgreSQL 14)
-- Cria o schema base e carrega os dados iniciais (seed).
-- Executado automaticamente pelo container apenas na PRIMEIRA
-- inicialização (volume de dados vazio).
-- ============================================================

BEGIN;

-- ==================== Tabelas ====================

-- Tabela users (SINGLE_TABLE inheritance com DTYPE)
CREATE TABLE public.users (
    id uuid NOT NULL,
    dtype character varying(31) NOT NULL DEFAULT 'USER',
    apartment character varying(255),
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    token_version integer NOT NULL DEFAULT 0,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- Tabela space
CREATE TABLE public.space (
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.space_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    type character varying(255),
    CONSTRAINT space_pkey PRIMARY KEY (id),
    CONSTRAINT space_type_check CHECK (((type)::text = ANY ((ARRAY['SALAO_FESTAS'::character varying, 'CHURRASQUEIRA'::character varying, 'ACADEMIA'::character varying, 'CAMPO_FUTEBOL'::character varying])::text[])))
);

-- Tabela reservation
CREATE TABLE public.reservation (
    id uuid NOT NULL,
    date date NOT NULL,
    status character varying(255),
    notes text,
    "createdAt" timestamp(6) without time zone,
    "canceledAt" timestamp(6) without time zone,
    user_id uuid NOT NULL,
    space_id bigint NOT NULL,
    CONSTRAINT reservation_pkey PRIMARY KEY (id),
    CONSTRAINT uk_user_date_space UNIQUE (user_id, date, space_id),
    CONSTRAINT fk_reservation_user FOREIGN KEY (user_id) REFERENCES public.users(id),
    CONSTRAINT fk_reservation_space FOREIGN KEY (space_id) REFERENCES public.space(id)
);

-- Tabela equipment
CREATE TABLE public.equipment (
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.equipment_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    name character varying(255) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT equipment_pkey PRIMARY KEY (id),
    CONSTRAINT equipment_name_key UNIQUE (name)
);

-- Tabela guest
CREATE TABLE public.guest (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    checked_in boolean NOT NULL DEFAULT false,
    "checkedInAt" timestamp(6) without time zone,
    reservation_id uuid NOT NULL,
    CONSTRAINT guest_pkey PRIMARY KEY (id),
    CONSTRAINT fk_guest_reservation FOREIGN KEY (reservation_id) REFERENCES public.reservation(id)
);

-- Tabela liability_term
CREATE TABLE public.liability_term (
    id uuid NOT NULL,
    content text NOT NULL,
    signed_by_resident boolean NOT NULL DEFAULT false,
    "signedAt" timestamp(6) without time zone,
    reservation_id uuid NOT NULL,
    CONSTRAINT liability_term_pkey PRIMARY KEY (id),
    CONSTRAINT uk_liability_term_reservation UNIQUE (reservation_id),
    CONSTRAINT fk_liability_term_reservation FOREIGN KEY (reservation_id) REFERENCES public.reservation(id)
);

-- Tabela delivery
CREATE TABLE public.delivery (
    id uuid NOT NULL,
    "userId" uuid NOT NULL,
    "protocolNumber" character varying(255),
    discrimination character varying(255),
    "createdAt" timestamp(6) without time zone NOT NULL,
    "createdBy" character varying(255) NOT NULL,
    "voucherKey" character varying(255) NOT NULL,
    "otherRecipient" character varying(255),
    status character varying(255) NOT NULL,
    "deliveredAt" timestamp(6) without time zone,
    "pickedUpBy" character varying(255),
    CONSTRAINT delivery_pkey PRIMARY KEY (id)
);

-- Tabela space_inspection
CREATE TABLE public.space_inspection (
    id uuid NOT NULL,
    type character varying(255) NOT NULL,
    notes text,
    "inspectedAt" timestamp(6) without time zone NOT NULL,
    reservation_id uuid NOT NULL,
    employee_id uuid NOT NULL,
    CONSTRAINT space_inspection_pkey PRIMARY KEY (id),
    CONSTRAINT fk_space_inspection_reservation FOREIGN KEY (reservation_id) REFERENCES public.reservation(id),
    CONSTRAINT fk_space_inspection_employee FOREIGN KEY (employee_id) REFERENCES public.users(id)
);

-- Tabela space_inspection_item
CREATE TABLE public.space_inspection_item (
    id uuid NOT NULL,
    "equipmentName" character varying(255) NOT NULL,
    ok_confirmed boolean NOT NULL,
    "photoUrl" character varying(255) NOT NULL,
    inspection_id uuid NOT NULL,
    CONSTRAINT space_inspection_item_pkey PRIMARY KEY (id),
    CONSTRAINT fk_space_inspection_item_inspection FOREIGN KEY (inspection_id) REFERENCES public.space_inspection(id)
);

-- Tabela occurrence
CREATE TABLE public.occurrence (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    description text NOT NULL,
    "incidentDate" timestamp(6) without time zone NOT NULL,
    "createdAt" timestamp(6) without time zone NOT NULL,
    CONSTRAINT occurrence_pkey PRIMARY KEY (id),
    CONSTRAINT fk_occurrence_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- Tabela announcements
CREATE TABLE public.announcements (
    id uuid NOT NULL,
    title character varying(255) NOT NULL,
    content character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT announcements_pkey PRIMARY KEY (id)
);

-- Tabela equipment_reservation
CREATE TABLE public.equipment_reservation (
    id uuid NOT NULL,
    equipment_id bigint NOT NULL,
    user_id uuid NOT NULL,
    date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    status character varying(255) NOT NULL,
    "createdAt" timestamp(6) without time zone NOT NULL,
    "pickedUpAt" timestamp(6) without time zone,
    "returnedAt" timestamp(6) without time zone,
    "canceledAt" timestamp(6) without time zone,
    CONSTRAINT equipment_reservation_pkey PRIMARY KEY (id),
    CONSTRAINT fk_equipment_reservation_equipment FOREIGN KEY (equipment_id) REFERENCES public.equipment(id),
    CONSTRAINT fk_equipment_reservation_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- Tabela token_blacklist
CREATE TABLE public.token_blacklist (
    id uuid NOT NULL,
    jti character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT token_blacklist_pkey PRIMARY KEY (id),
    CONSTRAINT uk_token_blacklist_jti UNIQUE (jti)
);

-- Tabela refresh_token
CREATE TABLE public.refresh_token (
    id uuid NOT NULL,
    token_hash character varying(255) NOT NULL,
    user_id uuid NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    revoked_at timestamp(6) without time zone,
    replaced_by uuid,
    CONSTRAINT refresh_token_pkey PRIMARY KEY (id),
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash)
);

-- Tabela push_subscriptions
CREATE TABLE public.push_subscriptions (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    endpoint character varying(1024) NOT NULL,
    p256dh character varying(255) NOT NULL,
    auth character varying(255) NOT NULL,
    CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id),
    CONSTRAINT fk_push_subscriptions_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- ==================== Seed de Dados ====================

-- Users (UUIDs fixos para reprodutibilidade)
-- Senha de todos os usuarios: senha123
INSERT INTO public.users (id, dtype, apartment, email, name, password, role, token_version) VALUES
    ('a1b2c3d4-e5f6-7890-abcd-ef1234567801', 'USER', '101A', 'morador1@email.com', 'Morador1', '$2a$10$BFLGM8yPeS10lsFDP6BUuuibcnSklSSzmzEyCv9JaXEaLPRLNvTKS', 'RESIDENT_ROLE', 0),
    ('a1b2c3d4-e5f6-7890-abcd-ef1234567802', 'USER', '202B', 'adm1@email.com', 'Administrador 1', '$2a$10$BFLGM8yPeS10lsFDP6BUuuibcnSklSSzmzEyCv9JaXEaLPRLNvTKS', 'ADMIN_ROLE', 0),
    ('a1b2c3d4-e5f6-7890-abcd-ef1234567803', 'USER', '303C', 'teste@email.com', 'Teste', '$2a$10$BFLGM8yPeS10lsFDP6BUuuibcnSklSSzmzEyCv9JaXEaLPRLNvTKS', 'RESIDENT_ROLE', 0),
    ('a1b2c3d4-e5f6-7890-abcd-ef1234567804', 'USER', '404D', 'teste2@email.com', 'Teste 2', '$2a$10$BFLGM8yPeS10lsFDP6BUuuibcnSklSSzmzEyCv9JaXEaLPRLNvTKS', 'RESIDENT_ROLE', 0),
    ('a1b2c3d4-e5f6-7890-abcd-ef1234567805', 'USER', '505E', 'zaira@email.com', 'Zaira', '$2a$10$BFLGM8yPeS10lsFDP6BUuuibcnSklSSzmzEyCv9JaXEaLPRLNvTKS', 'RESIDENT_ROLE', 0),
    ('a1b2c3d4-e5f6-7890-abcd-ef1234567806', 'USER', '606F', 'bruno@email.com', 'Bruno', '$2a$10$BFLGM8yPeS10lsFDP6BUuuibcnSklSSzmzEyCv9JaXEaLPRLNvTKS', 'ADMIN_ROLE', 0),
    ('a1b2c3d4-e5f6-7890-abcd-ef1234567807', 'USER', '707G', 'bruno.case@email.com', 'Bruno Case', '$2a$10$BFLGM8yPeS10lsFDP6BUuuibcnSklSSzmzEyCv9JaXEaLPRLNvTKS', 'EMPLOYEE', 0);

-- Spaces
INSERT INTO public.space (id, type) VALUES
    (1, 'SALAO_FESTAS'),
    (2, 'CHURRASQUEIRA'),
    (3, 'ACADEMIA'),
    (4, 'CAMPO_FUTEBOL');

-- Equipment
INSERT INTO public.equipment (id, name, active) VALUES
    (1, 'Televisão Comunitária', true);

-- Reservations (com UUIDs e user_id)
INSERT INTO public.reservation (id, date, user_id, space_id, status) VALUES
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567801', '2025-09-13', 'a1b2c3d4-e5f6-7890-abcd-ef1234567801', 1, 'CONFIRMED'),
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567802', '2024-05-02', 'a1b2c3d4-e5f6-7890-abcd-ef1234567801', 2, 'CONFIRMED'),
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567803', '2024-05-10', 'a1b2c3d4-e5f6-7890-abcd-ef1234567801', 2, 'CONFIRMED'),
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567804', '2024-08-10', 'a1b2c3d4-e5f6-7890-abcd-ef1234567801', 1, 'CONFIRMED'),
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567805', '2024-05-11', 'a1b2c3d4-e5f6-7890-abcd-ef1234567803', 1, 'CONFIRMED'),
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567806', '2025-08-28', 'a1b2c3d4-e5f6-7890-abcd-ef1234567804', 1, 'CONFIRMED'),
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567807', '2025-08-29', 'a1b2c3d4-e5f6-7890-abcd-ef1234567804', 1, 'CONFIRMED'),
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567808', '2025-08-30', 'a1b2c3d4-e5f6-7890-abcd-ef1234567804', 1, 'CONFIRMED'),
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567809', '2025-09-04', 'a1b2c3d4-e5f6-7890-abcd-ef1234567805', 1, 'CONFIRMED'),
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567810', '2025-09-20', 'a1b2c3d4-e5f6-7890-abcd-ef1234567801', 2, 'CONFIRMED'),
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567811', '2026-10-01', 'a1b2c3d4-e5f6-7890-abcd-ef1234567801', 1, 'PENDING'),
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567812', '2026-10-02', 'a1b2c3d4-e5f6-7890-abcd-ef1234567801', 1, 'PENDING'),
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567813', '2026-12-21', 'a1b2c3d4-e5f6-7890-abcd-ef1234567805', 2, 'PENDING'),
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567814', '2026-12-22', 'a1b2c3d4-e5f6-7890-abcd-ef1234567805', 2, 'PENDING');

-- ==================== Sequências ====================

SELECT pg_catalog.setval('public.space_id_seq', 4, true);
SELECT pg_catalog.setval('public.equipment_id_seq', 1, true);

COMMIT;
