-- ============================================================
-- LunaLink - Init Script (PostgreSQL 14)
-- Cria o schema base e carrega os dados iniciais (seed).
-- Executado automaticamente pelo container apenas na PRIMEIRA
-- inicialização (volume de dados vazio).
-- ============================================================

BEGIN;

-- ==================== Tabelas ====================

CREATE TABLE public.users (
    id bigint GENERATED ALWAYS AS IDENTITY (
        SEQUENCE NAME public.users_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    login character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    email character varying(255),
    name character varying(255),
    login_email character varying(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE public.resident (
    id bigint NOT NULL,
    CONSTRAINT resident_pkey PRIMARY KEY (id),
    CONSTRAINT fk_resident_users FOREIGN KEY (id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE public.administrator (
    id bigint NOT NULL,
    CONSTRAINT administrator_pkey PRIMARY KEY (id),
    CONSTRAINT fk_administrator_users FOREIGN KEY (id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE public.space (
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.space_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    type character varying(255),
    CONSTRAINT space_pkey PRIMARY KEY (id),
    CONSTRAINT space_type_check CHECK (((type)::text = ANY ((ARRAY['SALAO_FESTAS'::character varying, 'CHURRASQUEIRA'::character varying, 'ACADEMIA'::character varying])::text[])))
);

CREATE TABLE public.reservation (
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.reservation_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    date date NOT NULL,
    resident_id bigint NOT NULL,
    space_id bigint NOT NULL,
    CONSTRAINT reservation_pkey PRIMARY KEY (id),
    CONSTRAINT uk_resident_date UNIQUE (resident_id, date, space_id),
    CONSTRAINT fk_reservation_resident FOREIGN KEY (resident_id) REFERENCES public.resident(id),
    CONSTRAINT fk_reservation_space FOREIGN KEY (space_id) REFERENCES public.space(id)
);

CREATE TABLE public.monthly_reservations (
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.monthly_reservations_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    resident_id bigint NOT NULL,
    reservation_id bigint NOT NULL,
    creation_date timestamp(6) without time zone,
    CONSTRAINT monthly_reservations_pkey PRIMARY KEY (id),
    CONSTRAINT fk_monthly_reservations_resident FOREIGN KEY (resident_id) REFERENCES public.resident(id),
    CONSTRAINT fk_monthly_reservations_reservation FOREIGN KEY (reservation_id) REFERENCES public.reservation(id)
);

CREATE TABLE public.check_in_gym (
    id uuid NOT NULL,
    entrada timestamp(6) without time zone,
    resident_id bigint NOT NULL,
    space_id bigint NOT NULL,
    CONSTRAINT check_in_gym_pkey PRIMARY KEY (id),
    CONSTRAINT fk_check_in_gym_resident FOREIGN KEY (resident_id) REFERENCES public.resident(id),
    CONSTRAINT fk_check_in_gym_space FOREIGN KEY (space_id) REFERENCES public.space(id)
);

CREATE TABLE public.check_out_gym (
    id uuid NOT NULL,
    saida timestamp(6) without time zone,
    check_in_gym_id uuid,
    resident_id_id bigint,
    CONSTRAINT check_out_gym_pkey PRIMARY KEY (id),
    CONSTRAINT uk_check_out_gym_check_in UNIQUE (check_in_gym_id),
    CONSTRAINT fk_check_out_gym_check_in FOREIGN KEY (check_in_gym_id) REFERENCES public.check_in_gym(id),
    CONSTRAINT fk_check_out_gym_resident FOREIGN KEY (resident_id_id) REFERENCES public.resident(id)
);

CREATE TABLE public.delivery (
    id uuid NOT NULL,
    image bytea,
    name_resident character varying(255),
    protocol_number character varying(255),
    email_resident character varying(255),
    CONSTRAINT delivery_pkey PRIMARY KEY (id)
);

CREATE TABLE public.equipment (
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.equipment_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    name character varying(255) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT equipment_pkey PRIMARY KEY (id),
    CONSTRAINT equipment_name_key UNIQUE (name)
);

-- ==================== Seed de Dados ====================

INSERT INTO public.users (id, login, password, role, email, name, login_email) OVERRIDING SYSTEM VALUE VALUES
    (1, 'Morador1', '$2a$10$Rp.hwRqFUpVmdkfO1ce22uIzhN/ixlBr7n3pPd/N0CtLD7073WQRC', 'RESIDENT', NULL, NULL, NULL),
    (5, 'adm1', '$2a$10$O9gk9tk3KRKpzYUnx/KPkutCchGmIC1bcQFirdW/aUuQj6gT9/QR2', 'ADMINISTRATOR', NULL, NULL, NULL),
    (6, 'teste', '$2a$10$wfTvYmPuPw4l2F7zznWrAeZGsTCErDhxn/8dwuhwYLG6XmqK9ZjQu', 'RESIDENT', NULL, NULL, NULL),
    (7, 'teste2', '$2a$10$3wh.wGHFD0yYUD0cm.bPQeUp8W7iVBUcGjUrHxyssmaLJRnGWQPuu', 'RESIDENT', NULL, NULL, NULL),
    (9, 'zaira', '$2a$10$ruBefJsz95oE1bxrabu7mehejwMLLcYH29CaLUuFhAqEkr95fSIji', 'RESIDENT', NULL, NULL, NULL),
    (10, 'bruno', '$2a$10$GM1ZUziZ.5uS3cW5pqx4nuASVdEje3fr3cEOD7875Z9P8r.8tGYei', 'ADMINISTRATOR', NULL, NULL, NULL),
    (11, 'porteiro', '$2a$10$kCyrKBircbysiMWJ0A5u9OZF5ycsBh0JYuTgQBFg6oiEGMSZTn4H2', 'EMPLOYEE', NULL, NULL, NULL);

INSERT INTO public.resident (id) VALUES (1), (6), (7), (9), (11);

INSERT INTO public.administrator (id) VALUES (5), (10);

INSERT INTO public.space (id, type) VALUES
    (1, 'SALAO_FESTAS'),
    (2, 'CHURRASQUEIRA'),
    (3, 'ACADEMIA');

INSERT INTO public.equipment (id, name, active) VALUES
    (1, 'Televisão Comunitária', true);

INSERT INTO public.reservation (id, date, resident_id, space_id) VALUES
    (1, '2025-09-13', 1, 1),
    (5, '2024-05-02', 1, 2),
    (6, '2024-05-10', 1, 2),
    (8, '2024-08-10', 1, 1),
    (9, '2024-05-11', 6, 1),
    (10, '2025-08-28', 7, 1),
    (11, '2025-08-29', 7, 1),
    (12, '2025-08-30', 7, 1),
    (13, '2025-09-04', 9, 1),
    (20, '2025-09-20', 1, 2),
    (21, '2026-10-01', 1, 1),
    (22, '2026-10-02', 1, 1),
    (23, '2026-12-21', 9, 2),
    (24, '2026-12-22', 9, 2);

INSERT INTO public.monthly_reservations (id, resident_id, reservation_id, creation_date) VALUES
    (1, 1, 8, NULL),
    (2, 6, 9, NULL),
    (3, 7, 10, '2025-08-28 19:28:54'),
    (4, 7, 11, '2025-08-28 19:40:18'),
    (5, 7, 12, '2025-08-28 19:42:26'),
    (6, 9, 13, '2025-09-04 22:23:27'),
    (10, 1, 20, '2025-09-17 18:38:03'),
    (11, 1, 21, '2025-10-05 19:00:37'),
    (12, 1, 22, '2025-10-06 08:04:11'),
    (13, 9, 23, '2026-01-22 22:28:00'),
    (14, 9, 24, '2026-01-23 17:54:50');

INSERT INTO public.check_in_gym (id, entrada, resident_id, space_id) VALUES
    ('2381f882-6743-45e8-95ed-340bfbcdf784', '2025-09-27 10:30:15', 1, 3),
    ('e852adce-2696-4f3a-b53b-d401493760d3', '2025-09-27 10:30:15', 9, 3),
    ('cc24ad5f-e1c9-4bb8-add9-4c155a2dd572', '2025-09-28 10:30:15', 9, 3),
    ('3621b70b-7b17-45f6-9b94-42d6006df7dc', '2025-09-28 11:47:15', 9, 3),
    ('dd5c6ae1-a94b-4c04-b4b1-e861bf6b204b', '2025-10-28 11:47:15', 1, 3);

-- ==================== Sequências ====================

SELECT pg_catalog.setval('public.users_id_seq', 11, true);
SELECT pg_catalog.setval('public.space_id_seq', 12, true);
SELECT pg_catalog.setval('public.reservation_id_seq', 24, true);
SELECT pg_catalog.setval('public.monthly_reservations_id_seq', 14, true);
SELECT pg_catalog.setval('public.equipment_id_seq', 1, true);

COMMIT;
